/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "RPC.h"


#define HOSTNAME "192.168.0.107"
#define PROGRAM_NAME "RPC"
#define AUTHOR \
	proper_name(Marlon Brendo)

/*
-------------------------Header-----------------------------------------------------|

 AUTOR             : Marlon Brendo <marlonbrendo2013@gmail.com>
 DATA-DE-CRIAÇÃO   : 22/04/2021
 PROGRAMA          : RPC
 DESCRIÇÃO 	   : Utilizando RPC(Remote Procedure Call) para conferir respostas de
		     um questionário
 GITHUB		   : https://github.com/MarlonBrendonx?tab=repositories


------------------------------------------------------------------------------------|

*/



//-------------------------Cores------------------------------------------------------|

#define RED     "\x1b[31m"
#define GREEN   "\x1b[32m"
#define BLUE    "\x1b[34m"
#define YELLOW  "\x1b[33m"
#define END     "\x1b[0m"
#define INTERVAL 200



//------------------------------------------------------------------------------------|


static inline void emit_try_help(void){

	fprintf (stderr,("Try %s --help for more informations.\n"),PROGRAM_NAME);

}


void usage(int status){


	if( status != EXIT_SUCCESS )
		emit_try_help();
	
	else{

		fputs("Optional arguments: \n\
		   -h, --help  	       Show this help message and exit.\n\
		   -i, --interactive   Interactive questions.\n\
		   -s  --statistics    Show the statistics of the questions.\n\
		   ",stdout);

	}
	

}

results *corrected_questionnaire(parameters *prms,CLIENT *clnt){

	parameters *result;	
	results *r;

	r =corrected_questionnaire_100(prms,clnt);

	if (r == (results *) NULL) {
		clnt_perror (clnt, RED "[✗]" END " Falha na chamada!");
	}

	printf(BLUE "[°]" END " Numero da questao: %d\n",r->iquestion_number);
	printf(GREEN "[✓]" END " Respostas corretas: %d\n",r->icorrect_answers);
	printf(RED "[✗]" END   " Respostas erradas: %d\n",r->wrong_answers);

	clnt_destroy (clnt);

	exit(0);
}

results *statistics(CLIENT *clnt){
	
	char *statistics_100_arg;
	results  *result_2;
	result_2 = statistics_100((void*)&statistics_100_arg, clnt);

	
	if ( result_2 == NULL ) {

		fprintf(stderr,RED "[✗]" END " Houve um problema na chamada RPC ou a lista pode estar vazia!\n\n");
		exit(1);
	}

		
	results *p = result_2;

	
	printf(GREEN"--------------𝕊𝕥𝕒𝕥𝕚𝕤𝕥𝕚𝕔𝕤----------\n\n"END);  
      
	while(p!=NULL){
		
		printf(BLUE "\nQuestão [%d]-----------------------\n\n" END,p->iquestion_number);
		printf(GREEN "[✓]" END " Respostas corretas: %d\n",p->icorrect_answers);
		printf(RED "[✗]" END   " Respostas erradas: %d\n",p->wrong_answers);
		printf(BLUE "\n----------------------------------\n\n" END"\n");

		p=p->prox;
		

	}

	
	
	
	
}


int main (int argc, char *argv[]){

	char *host;

	CLIENT *clnt;
	parameters *prms;
	
			
	if( strcmp( argv[1], "-i") == 0 ){
	
		if(  argc != 5  ){

			fprintf(stderr,RED "[X]" END  " Parametros invalidos !\n"  );
			fprintf(stderr,"Use: %s <numero da questao> <numero de alternativas> <respostas>\n",argv[0]);
			

		}else if( atoi( argv[2] )  > 5 ){
		
			fprintf(stderr,RED "[X]" END  " Numero da questão invalida!\n"  );

		}else{
		
			/* Cria uma conexão com portmapper no host remoto e pergunta 
			   qual o número da porta do servidor RPC*/
			clnt = clnt_create(HOSTNAME, PROG, VERSAO, "udp");
	
			
			if ( clnt == NULL) {
				clnt_pcreateerror(HOSTNAME);
				exit(1); 
			}
			

			prms=malloc(sizeof(prms));

			prms->iquestion_number 	      = atoi( argv[2] );
			prms->inumber_of_alternatives = atoi( argv[3] );
			prms->answers		      = argv[4];
			
			
			corrected_questionnaire(prms,clnt);

		}

	
	}else if( strcmp( argv[1], "--help") == 0 ){

		usage(0);

	}else if( strcmp( argv[1], "-s") == 0 || strcmp( argv[1], "--statistics") == 0 ){
		
		clnt = clnt_create(HOSTNAME, PROG, VERSAO, "udp");

		if ( clnt == NULL) {
			clnt_pcreateerror(HOSTNAME);
			exit(1); 
		}
		
		statistics(clnt);

	}else
		usage(1);

	
	
exit (0);
}

